const state = { csrfToken: '', user: null };
const titles = { dashboard: 'Overview', users: 'Users', recharges: 'Recharge requests', accounts: 'Accounts & balances', transactions: 'Transactions', transfers: 'P2P transfers', swaps: 'Income swaps', withdrawals: 'Withdrawals', packages: 'Package plans', referrals: 'Referrals', rewards: 'Rewards', notifications: 'Notifications', support: 'Support', reports: 'Reports', 'audit-logs': 'Audit logs', 'payment-settings': 'Payment settings', settings: 'Settings' };
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const money = (minor) => `₹ ${(Number(minor || 0) / 100).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (value) => value ? new Date(value).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const badge = (value) => { const kind = ['ACTIVE', 'APPROVED', 'COMPLETED', 'SUCCESS', 'ISSUED', 'PAID', 'READY'].includes(value) ? 'good' : ['PENDING', 'INACTIVE'].includes(value) ? 'warn' : ['FAILED', 'SUSPENDED', 'REJECTED', 'ARCHIVED', 'REVERSED'].includes(value) ? 'bad' : ''; return `<span class="badge ${kind}">${escapeHtml(value || '—')}</span>`; };
function apiUrl(path) { const configured = String(window.__INFOTECH_API_URL__ || '').replace(/\/$/, ''); const local = (location.protocol === 'file:' || ['localhost', '127.0.0.1'].includes(location.hostname)) && location.port !== '8787' ? 'http://localhost:8787' : ''; return `${configured || local}${path}`; }
async function api(path, options = {}) { const headers = { ...(options.body ? { 'content-type': 'application/json' } : {}), ...options.headers }; if (state.csrfToken && options.method && options.method !== 'GET') headers['x-csrf-token'] = state.csrfToken; const response = await fetch(apiUrl(path), { credentials: 'include', ...options, headers }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || 'The request could not be completed.'); return payload; }
function setView(view) { const login = $('#login-view'); const app = $('#app-view'); const loginVisible = view === 'login'; login.hidden = !loginVisible; app.hidden = loginVisible; login.setAttribute('aria-hidden', String(!loginVisible)); app.setAttribute('aria-hidden', String(loginVisible)); login.inert = !loginVisible; app.inert = loginVisible; }
function showLogin(message = '') { setView('login'); $('#login-error').textContent = message; }
function showApp() { setView('app'); $('#admin-user').textContent = `${state.user.fullName} · ${state.user.email}`; }
function routeName() { const name = window.location.pathname.split('/')[2] || 'dashboard'; return titles[name] ? name : 'dashboard'; }
function go(route) { window.history.pushState({}, '', route === 'dashboard' ? '/admin' : `/admin/${route}`); void renderRoute(); }
function table(headers, rows) { if (!rows.length) return '<div class="empty">No records are available yet.</div>'; return `<div class="table-wrap"><table><thead><tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`; }
function panel(title, content) { return `<section class="panel"><div class="panel-header"><h2>${escapeHtml(title)}</h2></div>${content}</section>`; }
function statusError(error) { $('#page-status').textContent = error.message; $('#page-status').className = 'page-status error'; }

async function renderDashboard() { const data = await api('/api/admin/dashboard'); const m = data.metrics; const metrics = [['Total users', m.users.total], ['Active users', m.users.active], ['Pending recharges', m.recharges.pending], ['Today\'s recharges', m.recharges.today], ['Approved recharges', m.recharges.approved], ['Pending withdrawals', m.withdrawals.pending], ['Approved withdrawals', m.withdrawals.approved], ['Package activations', m.activations.count], ['Fund credits', money(m.fund.credits)], ['Fund debits', money(m.fund.debits)], ['Income credits', money(m.income.credits)], ['P2P transfers', m.transfers.count], ['Referrals', m.referrals.count], ['Open support tickets', m.tickets.open]]; const cards = `<div class="metric-grid">${metrics.map(([label, value]) => `<div class="metric"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`).join('')}</div>`; const activity = table(['Action', 'Target', 'Date'], data.activity.map((item) => `<tr><td>${escapeHtml(item.action)}</td><td>${escapeHtml(`${item.target_type || '—'} ${item.target_id || ''}`)}</td><td>${date(item.created_at)}</td></tr>`)); $('#page-content').innerHTML = `${cards}<div class="grid-2">${panel('Recent admin activity', activity)}${panel('Quick actions', '<div class="toolbar"><button class="button primary" data-go="recharges">Review recharge requests</button><button class="button" data-go="withdrawals">Review withdrawals</button><button class="button" data-go="payment-settings">Payment settings</button></div>')}</div>`; }
async function renderUsers() { const data = await api('/api/admin/users'); const rows = data.data.map((user) => `<tr><td>${escapeHtml(user.user_id)}</td><td>${escapeHtml(user.full_name)}<br><span class="muted">${escapeHtml(user.email)}</span></td><td>${badge(user.role)}</td><td>${badge(user.status)}</td><td>${date(user.created_at)}</td><td><button class="button small" data-user-status="${user.id}" data-status="${user.status === 'SUSPENDED' ? 'ACTIVE' : 'SUSPENDED'}">${user.status === 'SUSPENDED' ? 'Reactivate' : 'Suspend'}</button></td></tr>`); $('#page-content').innerHTML = panel('User accounts', `<div class="toolbar"><label>Search<input id="user-search" placeholder="Name, email, or ID" /></label><button class="button primary" data-user-search>Search</button></div>${table(['User ID', 'User', 'Role', 'Status', 'Registered', 'Action'], rows)}`); }
async function renderRecharges() { const data = await api('/api/admin/recharges'); const rows = data.data.map((item) => `<tr><td>${escapeHtml(item.user_id)}<br><span class="muted">${escapeHtml(item.email)}</span></td><td>${money(item.amount_minor)}</td><td>${escapeHtml(item.payment_reference)}</td><td>${badge(item.status)}</td><td>${date(item.submitted_at)}</td><td>${item.status === 'PENDING' ? `<button class="button small" data-recharge-review="${item.id}" data-status="APPROVED">Approve</button> <button class="button small" data-recharge-review="${item.id}" data-status="REJECTED">Reject</button>` : escapeHtml(item.admin_note || 'Reviewed')}</td></tr>`); $('#page-content').innerHTML = panel('Manual QR recharge requests', table(['User', 'Amount', 'UTR / reference', 'Status', 'Submitted', 'Review'], rows)); }
async function renderWithdrawals() { const data = await api('/api/admin/withdrawals'); const rows = data.data.map((item) => `<tr><td>${escapeHtml(item.user_id)}<br><span class="muted">${escapeHtml(item.email)}</span></td><td>${money(item.amount_minor)}</td><td>${money(item.payable_minor)}</td><td>${escapeHtml(item.payment_details)}</td><td>${badge(item.status)}</td><td>${item.status === 'PENDING' ? `<button class="button small" data-withdrawal-review="${item.id}" data-status="APPROVED">Approve</button> <button class="button small" data-withdrawal-review="${item.id}" data-status="REJECTED">Reject</button>` : escapeHtml(item.admin_note || 'Reviewed')}</td></tr>`); $('#page-content').innerHTML = panel('Withdrawal requests', table(['User', 'Amount', 'Payable', 'Payment details', 'Status', 'Review'], rows)); }
async function renderPaymentSettings() { const data = await api('/api/admin/payment-settings'); const settings = data.settings || {}; $('#page-content').innerHTML = panel('Manual QR payment settings', `<form id="payment-settings-form" class="stack-form"><label>QR payload or image URL<input name="qrPayload" value="${escapeHtml(settings.qr_payload)}" /></label><label>Account name<input name="accountName" value="${escapeHtml(settings.account_name)}" /></label><label>Instructions<textarea name="instructions" rows="4">${escapeHtml(settings.instructions)}</textarea></label><label>Minimum recharge<input name="minimumAmount" type="number" min="1" step="0.01" value="${Number(settings.minimum_amount_minor || 100) / 100}" /></label><label>Maximum recharge<input name="maximumAmount" type="number" min="1" step="0.01" value="${settings.maximum_amount_minor ? Number(settings.maximum_amount_minor) / 100 : ''}" /></label><label><input name="enabled" type="checkbox" ${settings.enabled ? 'checked' : ''} /> Accept recharge requests</label><button class="button primary" type="submit">Save settings</button></form>`); }
async function renderPackages() { const data = await api('/api/admin/packages'); const rows = data.data.map((item) => `<tr><td>${badge(item.kind)}</td><td>${escapeHtml(item.name)}</td><td>${money(item.amount_minor)}</td><td>${item.duration_days}</td><td>${money(item.total_return_minor)}</td><td>${badge(item.status)}</td><td><button class="button small" data-package-status="${item.id}" data-status="${item.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'}">${item.status === 'ACTIVE' ? 'Deactivate' : 'Activate'}</button></td></tr>`); $('#page-content').innerHTML = panel('Package plans', `<form id="package-form" class="inline-form"><label>Type<select name="kind"><option>BASIC</option><option>FD</option></select></label><label>Name<input name="name" required /></label><label>Amount<input name="amount" type="number" min="1" step="0.01" required /></label><label>Daily ROI<input name="dailyRoi" type="number" min="0" step="0.01" value="0" /></label><label>Days<input name="durationDays" type="number" min="1" required /></label><label>Total return<input name="totalReturn" type="number" min="1" step="0.01" required /></label><button class="button primary" type="submit">Add plan</button></form>${table(['Type', 'Name', 'Amount', 'Days', 'Total return', 'Status', 'Action'], rows)}`); }
async function renderReports() { const data = await api('/api/admin/reports'); $('#page-content').innerHTML = `<div class="metric-grid"><div class="metric"><span>Users</span><strong>${data.users.count}</strong></div><div class="metric"><span>Activations</span><strong>${data.activations.count}</strong></div><div class="metric"><span>Transfer volume</span><strong>${money(data.transfers.amount_minor)}</strong></div></div><div class="grid-2">${panel('Recharge summary', table(['Status', 'Count', 'Amount'], data.recharges.map((item) => `<tr><td>${badge(item.status)}</td><td>${item.count}</td><td>${money(item.amount_minor)}</td></tr>`)))}${panel('Withdrawal summary', table(['Status', 'Count', 'Amount'], data.withdrawals.map((item) => `<tr><td>${badge(item.status)}</td><td>${item.count}</td><td>${money(item.amount_minor)}</td></tr>`)))}</div>`; }
async function renderSettings() { const data = await api('/api/admin/settings'); $('#page-content').innerHTML = panel('Platform settings', '<p class="muted">Secret values are never shown in the admin panel.</p>' + table(['Integration', 'Status'], Object.entries(data.integrations).map(([name, ready]) => `<tr><td>${escapeHtml(name)}</td><td>${ready ? badge('READY') : badge('NOT CONFIGURED')}</td></tr>`))); }
async function renderSimple(route) { const endpoints = { accounts: '/api/admin/accounts', transactions: '/api/admin/transactions', transfers: '/api/admin/transfers', swaps: '/api/admin/swaps', referrals: '/api/admin/referrals', rewards: '/api/admin/rewards', notifications: '/api/admin/notifications', support: '/api/admin/support', 'audit-logs': '/api/admin/audit-logs' }; const data = await api(endpoints[route]); const keys = Object.keys(data.data[0] || {}); const rows = data.data.map((item) => `<tr>${keys.map((key) => `<td>${key.endsWith('_at') || key === 'created_at' || key === 'updated_at' ? date(item[key]) : key.includes('minor') || key === 'amount' ? money(item[key]) : ['status', 'type', 'direction'].includes(key) ? badge(item[key]) : escapeHtml(item[key] ?? '—')}</td>`).join('')}</tr>`); $('#page-content').innerHTML = panel(titles[route], table(keys.map((key) => key.replaceAll('_', ' ')), rows)); }
async function renderRoute() { const route = routeName(); $('#page-title').textContent = titles[route]; document.querySelectorAll('#admin-nav a').forEach((link) => link.classList.toggle('active', link.dataset.route === route)); $('#page-status').textContent = 'Loading…'; $('#page-status').className = 'page-status'; try { if (route === 'dashboard') await renderDashboard(); else if (route === 'users') await renderUsers(); else if (route === 'recharges') await renderRecharges(); else if (route === 'withdrawals') await renderWithdrawals(); else if (route === 'payment-settings') await renderPaymentSettings(); else if (route === 'packages') await renderPackages(); else if (route === 'reports') await renderReports(); else if (route === 'settings') await renderSettings(); else await renderSimple(route); $('#page-status').textContent = ''; } catch (error) { statusError(error); $('#page-content').innerHTML = ''; } }

document.addEventListener('click', async (event) => {
  const goButton = event.target.closest('[data-go]');
  if (goButton) return go(goButton.dataset.go);
  const link = event.target.closest('[data-route]');
  if (link) { event.preventDefault(); return go(link.dataset.route); }
  const userButton = event.target.closest('[data-user-status]');
  if (userButton) { try { await api(`/api/admin/users/${userButton.dataset.userStatus}/status`, { method: 'PATCH', body: JSON.stringify({ status: userButton.dataset.status }) }); await renderRoute(); } catch (error) { statusError(error); } }
  const rechargeButton = event.target.closest('[data-recharge-review]');
  if (rechargeButton) { try { await api(`/api/admin/recharges/${rechargeButton.dataset.rechargeReview}/review`, { method: 'PATCH', body: JSON.stringify({ status: rechargeButton.dataset.status }) }); await renderRoute(); } catch (error) { statusError(error); } }
  const withdrawalButton = event.target.closest('[data-withdrawal-review]');
  if (withdrawalButton) { try { await api(`/api/admin/withdrawals/${withdrawalButton.dataset.withdrawalReview}/review`, { method: 'PATCH', body: JSON.stringify({ status: withdrawalButton.dataset.status }) }); await renderRoute(); } catch (error) { statusError(error); } }
  const packageButton = event.target.closest('[data-package-status]');
  if (packageButton) { try { await api(`/api/admin/packages/${packageButton.dataset.packageStatus}`, { method: 'PATCH', body: JSON.stringify({ status: packageButton.dataset.status }) }); await renderRoute(); } catch (error) { statusError(error); } }
});
document.addEventListener('submit', async (event) => { if (event.target.id === 'login-form') { event.preventDefault(); const form = new FormData(event.target); try { const data = await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); state.user = data.user; state.csrfToken = data.csrfToken; showApp(); go('dashboard'); } catch (error) { showLogin(error.message); } } if (event.target.id === 'payment-settings-form') { event.preventDefault(); const form = new FormData(event.target); try { await api('/api/admin/payment-settings', { method: 'PATCH', body: JSON.stringify({ qrPayload: form.get('qrPayload'), accountName: form.get('accountName'), instructions: form.get('instructions'), minimumAmount: form.get('minimumAmount'), maximumAmount: form.get('maximumAmount'), enabled: form.get('enabled') === 'on' }) }); await renderRoute(); } catch (error) { statusError(error); } } if (event.target.id === 'package-form') { event.preventDefault(); const form = new FormData(event.target); try { await api('/api/admin/packages', { method: 'POST', body: JSON.stringify(Object.fromEntries(form.entries())) }); await renderRoute(); } catch (error) { statusError(error); } } });
$('#logout-button').addEventListener('click', async () => { try { await api('/api/admin/logout', { method: 'POST' }); } finally { state.user = null; state.csrfToken = ''; window.history.replaceState({}, '', '/admin/login'); showLogin(); } });
window.addEventListener('popstate', renderRoute);
try { const session = await api('/api/admin/me'); state.user = session.user; state.csrfToken = session.csrfToken; if (window.location.pathname === '/admin/login') window.history.replaceState({}, '', '/admin'); showApp(); await renderRoute(); } catch { showLogin(); }
